//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilausDBAdvancedMVCPalautus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriat
    {
        public int KategoriaID { get; set; }
        public string KategoriaNimi { get; set; }
    }
}
